# Game Screen
SCREEN_DIM = (1080, 1920)
FPS = 60

TILE_DIM = (64, 64)
STATS_BAR_RATIO = (4,1)
SPACING = 10
BACKGROUND_COLOR = (0, 48, 59)

PLAYER_STATS_BAR_SIZE = 50
PLAYER_STATS_BAR_DIM = (PLAYER_STATS_BAR_SIZE * STATS_BAR_RATIO[0], PLAYER_STATS_BAR_SIZE * STATS_BAR_RATIO[1])
ENEMY_STATS_BAR_SIZE = 20
ENEMY_STATS_BAR_DIM = (ENEMY_STATS_BAR_SIZE * STATS_BAR_RATIO[0], ENEMY_STATS_BAR_SIZE * STATS_BAR_RATIO[1])

CROSS_HAIR_DIM = (50, 50)

SCORE_DIGIT_RATIO = [24, 42]
SCORE_DIGITS_SIZE = 1
SCORE_DIGITS_DIM = [SCORE_DIGITS_SIZE*SCORE_DIGIT_RATIO[0], SCORE_DIGITS_SIZE*SCORE_DIGIT_RATIO[1]]

# Player Settings
PLAYER_ANIMATION_NAMES = ["up", "down", "left", "right", "up_idle", "down_idle", "left_idle", "right_idle"]
PLAYER_GRAPHICS_PATH = "./graphics/player/"
PLAYER_ANIMATION_SPEED = 0.15
PLAYER_WALK_SPEED = TILE_DIM[0] / 7
PLAYER_HEALTH = 4
PLAYER_DAMAGE_COOLDOWN = 1
PLAYER_SPAWN_IMMUNITY_TIME = 0


# Slime Settings
SLIME_ANIMATION_NAMES = ["slime_animation"]
SLIME_GRAPHICS_PATH = "./graphics/slime/"
SLIME_ANIMATION_SPEED = 0.15
SLIME_WALK_SPEED = 0.7 * PLAYER_WALK_SPEED
SLIME_HEALTH = 4
SLIME_DAMAGE_COOLDOWN = 1

ENEMY_TIME_BEFORE_ATTACK = 3


# Room Settings
STARTING_ROOM_DIM = [7,5]
OBSTACLE_TILES = ["wall", "gate"]


# Enemy Spawn info
MIN_DIST = 8