# Game Screen
TILE_DIM = (64, 64)
STATS_BAR_RATIO = (4,1)
STATS_BAR_SIZE = 50
STATS_BAR_DIM = (STATS_BAR_SIZE*STATS_BAR_RATIO[0], STATS_BAR_SIZE*STATS_BAR_RATIO[1])
CROSS_HAIR_DIM = (32, 32)
SCREEN_DIM = (1080, 1920)
FPS = 60

# Cool downs
HEALTHBAR_COOLDOWN = 1


# Rooms
STARTING_ROOM_DIM = [7,5]
OBSTACLE_TILES = ["wall", "gate"]


# Enemy Spawn info
MIN_DIST = 8



