# Game Screen
TILE_DIM = (64, 64)
STATS_BAR_RATIO = (4,1)
PLAYER_STATS_BAR_SIZE = 50
ENEMY_STATS_BAR_SIZE = 20
PLAYER_STATS_BAR_DIM = (PLAYER_STATS_BAR_SIZE * STATS_BAR_RATIO[0], PLAYER_STATS_BAR_SIZE * STATS_BAR_RATIO[1])
ENEMY_STATS_BAR_DIM = (ENEMY_STATS_BAR_SIZE * STATS_BAR_RATIO[0], ENEMY_STATS_BAR_SIZE * STATS_BAR_RATIO[1])
CROSS_HAIR_DIM = (50, 50)
SCREEN_DIM = (1080, 1920)
FPS = 60

# Cool downs
HEALTHBAR_COOLDOWN = 1
ENEMY_TIME_BEFORE_ATTACK = 3


# Rooms
STARTING_ROOM_DIM = [7,5]
OBSTACLE_TILES = ["wall", "gate"]


# Enemy Spawn info
MIN_DIST = 8



